# Generated by Django 3.2.6 on 2021-09-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.IntegerField()),
                ('user', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=2000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
